#231 use different browser instances for before after methods
Xceptance/neodymium pull request #232
Opened 2023-11-09 12:14 UTC by oomelianchuk

2024-03-28 09:00 UTC, wurzelkuchen requested changes
Small formal things

2024-11-11 08:52 UTC, oomelianchuk commented on src/main/java/com/xceptance/neodymium/module/statement/browser/multibrowser/DontStartNewBrowserForCleanUp.java
> +public @interface DontStartNewBrowserForCleanUp
javadock added

2024-11-11 08:53 UTC, oomelianchuk commented on src/test/java/com/xceptance/neodymium/testclasses/softassertion/UseSoftAssertions.java
> +        System.out.println("after");
removed

2024-12-04 09:47 UTC, wurzelkuchen requested changes
some additional notes

2024-12-04 09:47 UTC, wurzelkuchen commented on src/main/java/com/xceptance/neodymium/common/browser/BrowserAfterRunner.java
> +        // if @After method is annotated with @SuppressBrowser annotation, no new browser should be started
the code does not reflect what the comment demands here or did I see this wrong?

2024-12-04 09:47 UTC, wurzelkuchen commented on src/main/java/com/xceptance/neodymium/common/browser/BrowserBeforeRunner.java
> +        // if @Before method is annotated with @SuppressBrowser annotation, no new browser should be started
again the code does not do what the comment demands, does it? there is no check for suppressBrowser here

2024-12-04 11:59 UTC, wurzelkuchen approved these changes

2024-12-04 11:59 UTC, merged