Support lighthouse reports
Xceptance/neodymium pull request #310
Opened 2024-11-18 08:23 UTC by kqmpetenz

added the possibility to create lighthouse reports

2024-11-21 13:23 UTC, wurzelkuchen requested changes
nice work, now for the polishing ;)

2024-11-21 13:23 UTC, wurzelkuchen commented on src/main/java/com/xceptance/neodymium/util/LighthouseUtils.java
> +    public static void createLightHouseReport(WebDriver driver, String reportName) throws Exception
We should make the interface as simple as possible. There is no need to have the webdriver given as a parameter. Just use `Neodymium.getWebdriver()` inside this method.

2024-11-21 13:23 UTC, wurzelkuchen commented on src/test/java/com/xceptance/neodymium/util/LighthouseUtilsTest.java
> +            builder = new ProcessBuilder("fabricatedHtml > target/lighthouseUtilsReport.report.html");
this needs to be changed to `new ProcessBuilder("sh", "-c", "echo fabricatedHtml > target/lighthouseUtilsReport.report.html");`

2024-11-21 13:23 UTC, wurzelkuchen commented on src/main/java/com/xceptance/neodymium/util/LighthouseUtils.java
> +            builder = new ProcessBuilder(Neodymium.configuration().lighthouseBinaryPath(), "--chrome-flags=\"--ignore-certificate-errors\"", URL, "--port=" + Neodymium.getRemoteDebuggingPort(), "--pr
for linux please change this to call the shell by using `new ProcessBuilder("sh", "-c", Neodymium.config....`

2024-11-21 13:23 UTC, wurzelkuchen commented on src/main/java/com/xceptance/neodymium/util/LighthouseUtils.java
> +                new ProcessBuilder(Neodymium.configuration().lighthouseBinaryPath(), "--version").start();
for linux please change this to call the shell by using `new ProcessBuilder("sh", "-c", Neodymium.config....`

2024-11-22 09:53 UTC, kqmpetenz reviewed
only the documentation of the audits property and the link to the documentation in the neo config (when finished)

2024-11-22 09:53 UTC, kqmpetenz commented on config/neodymium.properties
> +neodymium.lighthouse.binaryPath = lighthouse
done

2024-11-22 09:53 UTC, kqmpetenz commented on config/neodymium.properties
> +neodymium.lighthouse.assert.thresholdScore.performance = 0.5
done

2024-11-22 09:53 UTC, kqmpetenz commented on config/neodymium.properties
> +#neodymium.lighthouse.assert.audits =
documentation is still todo

2024-11-22 09:53 UTC, kqmpetenz commented on src/main/java/com/xceptance/neodymium/util/LighthouseUtils.java
> + * Powered by <a href="https://developer.chrome.com/docs/lighthouse/overview?hl=de">Lighthouse</a> (Copyright Google)
done

2024-11-22 09:53 UTC, kqmpetenz commented on src/main/java/com/xceptance/neodymium/util/LighthouseUtils.java
> +            Assert.assertTrue("the performance score " + performanceScore + " doesn't exceed nor match the required threshold of " + Neodymium.configuration().lighthouseAssertPerformance() + ", pleas
1. done
2. done

2024-11-22 09:53 UTC, kqmpetenz commented on src/main/java/com/xceptance/neodymium/util/LighthouseUtils.java
> +        Allure.addAttachment(reportName, "text/html", FileUtils.openInputStream(new File("target/" + reportName + ".report.html")), "html");
done

2024-11-22 09:53 UTC, kqmpetenz commented on src/main/java/com/xceptance/neodymium/util/LighthouseUtils.java
> +                throw new Exception("the following audits " + errorAudits + " contain errors that need to be fixed, please look into the corresponding html for further information");
nope, done

2024-11-22 09:53 UTC, kqmpetenz commented on src/main/java/com/xceptance/neodymium/util/LighthouseUtils.java
> +                throw new Exception("the following audits " + errorAudits + " contain errors that need to be fixed, please look into the corresponding html for further information");
done

2024-11-22 12:48 UTC, kqmpetenz commented on config/neodymium.properties
> +#neodymium.lighthouse.assert.audits =
done

2024-11-29 08:54 UTC, wurzelkuchen requested changes

2024-12-03 08:59 UTC, wurzelkuchen approved these changes

2024-12-03 09:03 UTC, merged