Improvement: Stabilize unit tests #330
Xceptance/neodymium pull request #332
Opened 2024-12-23 15:47 UTC by oomelianchuk

2025-01-02 09:17 UTC, RobertAvemarg approved these changes

2025-01-22 06:34 UTC, wurzelkuchen commented
BrowserstackProxyTest.testBrowserstackProxySuccess and BrowserstackTest.testBrowserstack fail, due to changes on the xceptance web page. Please fix.

2025-01-22 08:32 UTC, wurzelkuchen requested changes
need to adjust browserstack test cases, which fail due to changes on XC website

2025-01-30 14:43 UTC, closed without merging

2025-01-30 14:43 UTC, wurzelkuchen commented
for some reasons git is messed up in this branch and will rollback certain changes if we merge it. Opened new branch and new pull request